[theme]
primaryColor="#9966ff"
backgroundColor="#ffffff"
secondaryBackgroundColor="#a66cff"
textColor="#000000"
font = "sans serif"

[server]
headless = true
fileWatcherType = "poll"   # evita erro de inotify em produção